[package]
name = "pseudocode"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
# or "z"
opt-level = "s"

[dependencies]
clap = { version = "3.2", features = ["derive"] }